package angeldx.to;
// Generated 25/10/2013 05:54:58 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name="estudiante"
    ,catalog="dbconcurso"
)
public class Estudiante  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private int dni;
     private String tcolegio;
     private String ncolegio;
     private String categoria;
     private double puntaje;
     private String asistencia;
     private Date fecha;

    public Estudiante() {
    }
    
    public Estudiante(String nombres, String apellidos, int dni, String tcolegio, String ncolegio, String categoria, double puntaje, String asistencia) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.dni = dni;
        this.tcolegio = tcolegio;
        this.ncolegio = ncolegio;
        this.categoria = categoria;
        this.puntaje = puntaje;
        this.asistencia = asistencia;
    }
    public Estudiante(String nombres, String apellidos, int dni, String tcolegio, String ncolegio, String categoria, double puntaje, String asistencia, Date fecha) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
       this.tcolegio = tcolegio;
       this.ncolegio = ncolegio;
       this.categoria = categoria;
       this.puntaje = puntaje;
       this.asistencia = asistencia;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="dni", nullable=false)
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }

    
    @Column(name="tcolegio", nullable=false, length=20)
    public String getTcolegio() {
        return this.tcolegio;
    }
    
    public void setTcolegio(String tcolegio) {
        this.tcolegio = tcolegio;
    }

    
    @Column(name="ncolegio", nullable=false, length=60)
    public String getNcolegio() {
        return this.ncolegio;
    }
    
    public void setNcolegio(String ncolegio) {
        this.ncolegio = ncolegio;
    }

    
    @Column(name="categoria", nullable=false, length=20)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="puntaje", nullable=false, precision=22, scale=0)
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }

    
    @Column(name="asistencia", nullable=false, length=2)
    public String getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(String asistencia) {
        this.asistencia = asistencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


